'use client';

import { useCallback } from 'react';

interface DownloadPdfButtonProps {
  toolName: string;
  content: string;
}

function markdownToHtml(markdown: string): string {
  return markdown
    .replace(/^### (.+)$/gm, '<h3 style="font-size:16px;font-weight:700;color:#1a1a2e;margin:20px 0 8px 0;">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="font-size:18px;font-weight:700;color:#1a1a2e;margin:24px 0 10px 0;">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 style="font-size:22px;font-weight:700;color:#1a1a2e;margin:28px 0 12px 0;">$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^\* (.+)$/gm, '<li style="margin:4px 0;">$1</li>')
    .replace(/^- (.+)$/gm, '<li style="margin:4px 0;">$1</li>')
    .replace(/(<li[\s\S]*?<\/li>\n?)+/g, '<ul style="padding-left:20px;margin:8px 0;">$&</ul>')
    .replace(/^\d+\. (.+)$/gm, '<div style="padding-left:16px;margin:4px 0;">$&</div>')
    .replace(/^---$/gm, '<hr style="border:none;border-top:1px solid #e5e7eb;margin:16px 0;">')
    .replace(/\n\n/g, '<br><br>')
    .replace(/\n/g, '<br>');
}

export default function DownloadPdfButton({ toolName, content }: DownloadPdfButtonProps) {
  const handleDownloadPdf = useCallback(async () => {
    const html2pdf = (await import('html2pdf.js')).default;

    const container = document.createElement('div');
    container.style.fontFamily = "'Inter', 'Segoe UI', sans-serif";
    container.style.padding = '40px';
    container.style.color = '#1a1a2e';
    container.style.lineHeight = '1.7';
    container.style.maxWidth = '800px';
    container.style.margin = '0 auto';

    // Header
    const header = document.createElement('div');
    header.style.borderBottom = '3px solid #8b5cf6';
    header.style.paddingBottom = '16px';
    header.style.marginBottom = '24px';

    const title = document.createElement('h1');
    title.textContent = toolName;
    title.style.fontSize = '24px';
    title.style.fontWeight = '700';
    title.style.color = '#8b5cf6';
    title.style.margin = '0 0 4px 0';
    header.appendChild(title);

    const subtitle = document.createElement('p');
    subtitle.textContent = `Generated by AI Career Tools • ${new Date().toLocaleDateString()}`;
    subtitle.style.fontSize = '12px';
    subtitle.style.color = '#9ca3af';
    subtitle.style.margin = '0';
    header.appendChild(subtitle);

    container.appendChild(header);

    // Content
    const body = document.createElement('div');
    body.style.fontSize = '14px';
    body.style.lineHeight = '1.8';

    body.innerHTML = markdownToHtml(content);
    container.appendChild(body);

    const opt = {
      margin: [10, 10, 10, 10] as [number, number, number, number],
      filename: `${toolName.replace(/\s+/g, '-').toLowerCase()}.pdf`,
      image: { type: 'jpeg' as const, quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'mm' as const, format: 'a4' as const, orientation: 'portrait' as const },
    };

    html2pdf().set(opt).from(container).save();
  }, [toolName, content]);

  return (
    <button
      onClick={handleDownloadPdf}
      className="flex items-center gap-2 px-4 py-2.5 bg-gray-900 text-white rounded-xl text-sm font-medium hover:bg-gray-800 transition-all duration-200 border border-white/10"
      title="Download as PDF"
    >
      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      Download PDF
    </button>
  );
}
