'use client';

import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div className="min-h-screen">
      <nav className="fixed top-0 left-0 right-0 z-50 glass-dark">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16 md:h-20">
            <Link href="/" className="flex items-center gap-2">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center">
                <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
              </div>
              <span className="text-xl font-bold gradient-text hidden sm:block">AI Career Tools</span>
            </Link>
            <Link href="/" className="btn-primary text-sm py-2 px-6">
              Back to Home
            </Link>
          </div>
        </div>
      </nav>

      <main className="pt-32 pb-20 px-4">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold mb-8">
            <span className="gradient-text">Terms of Service</span>
          </h1>
          
          <div className="glass rounded-2xl p-8 space-y-8">
            <section>
              <h2 className="text-2xl font-bold mb-4">Acceptance of Terms</h2>
              <p className="text-gray-300 leading-relaxed">
                By accessing and using AI Career Tools, you accept and agree to be bound by the terms and 
                conditions of this agreement. If you do not agree with any part of these terms, please do 
                not use our services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Free to Use</h2>
              <p className="text-gray-300 leading-relaxed">
                AI Career Tools is provided free of charge. You may use our AI-powered tools to generate 
                resumes, cover letters, emails, and other career-related content at no cost. We reserve 
                the right to modify or discontinue the service at any time without notice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">No Guarantee on Output Accuracy</h2>
              <p className="text-gray-300 leading-relaxed">
                The content generated by our AI tools is produced using Google&apos;s Gemini AI. While we strive 
                to provide high-quality, useful content, we make no guarantees regarding the accuracy, 
                completeness, or suitability of the generated output. AI-generated content should be reviewed 
                and edited by the user before professional use. Users should verify all information independently.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">User Responsibility</h2>
              <p className="text-gray-300 leading-relaxed">
                You are solely responsible for:
              </p>
              <ul className="list-disc list-inside text-gray-300 mt-4 space-y-2">
                <li>The content you create using our tools</li>
                <li>Reviewing and verifying all generated content before use</li>
                <li>Ensuring your use of generated content complies with applicable laws and regulations</li>
                <li>Any decisions made based on the information provided by our AI tools</li>
                <li>Maintaining the confidentiality of any information you choose to share</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Acceptable Use</h2>
              <p className="text-gray-300 leading-relaxed">
                You agree not to use our services to:
              </p>
              <ul className="list-disc list-inside text-gray-300 mt-4 space-y-2">
                <li>Generate false, misleading, or fraudulent content</li>
                <li>Create content that infringes on intellectual property rights</li>
                <li>Produce content for illegal or unethical purposes</li>
                <li>Attempt to reverse engineer or exploit our AI systems</li>
                <li>Use automated systems to access our services without authorization</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Intellectual Property</h2>
              <p className="text-gray-300 leading-relaxed">
                The content you generate using AI Career Tools belongs to you. However, we do not claim 
                ownership of the prompts or inputs you provide. You are responsible for ensuring you 
                have the right to use any information you submit to our tools.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Limitation of Liability</h2>
              <p className="text-gray-300 leading-relaxed">
                AI Career Tools and its operators shall not be held liable for any direct, indirect, 
                incidental, or consequential damages arising from the use of our services. This includes, 
                but is not limited to, damages arising from reliance on AI-generated content or loss of 
                data or business opportunities.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Service Availability</h2>
              <p className="text-gray-300 leading-relaxed">
                We do not guarantee uninterrupted access to our services. The availability of our AI tools 
                may be affected by maintenance, updates, or circumstances beyond our control.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Third-Party Services</h2>
              <p className="text-gray-300 leading-relaxed">
                Our services rely on Google&apos;s Gemini AI for content generation and Google AdSense for 
                advertising. We are not responsible for the practices or policies of these third-party 
                services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Changes to Terms</h2>
              <p className="text-gray-300 leading-relaxed">
                We reserve the right to modify these terms at any time. Continued use of our services 
                after any changes constitutes acceptance of the modified terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Contact</h2>
              <p className="text-gray-300 leading-relaxed">
                If you have any questions about these terms, please contact us at{' '}
                <a href="mailto:contact@aicareertools.in" className="text-violet-400 hover:underline">
                  contact@aicareertools.in
                </a>.
              </p>
            </section>
          </div>
        </div>
      </main>

      <footer className="py-8 px-4 border-t border-white/10">
        <div className="max-w-7xl mx-auto text-center">
          <p className="text-gray-500 text-sm">&copy; 2025 AI Career Tools - All rights reserved</p>
        </div>
      </footer>
    </div>
  );
}
